### ISSUE TITLE
Milestone 2.1

### ISSUE THREAD

**Issue by calendulish** [ShyPixie/steam-tools#12]
TODO

- [X] Fix autobuild
- [ ] Fix autobuild artifacts
- [X] Fix steamgifts_join giveaways type list
- [ ] Optimize timers for speed [20%]
- [X] Fix command line help descriptions
- [ ] Update Copyright headers
- [ ] Fix minor problems with exceptions not catched
- [ ] Enable QA validation again
- [ ] Finish basic functionality of authenticator module
- [ ] Finish basic functionality of auto trade module
- [ ] Fix anti-ban progress bar (already fixed?)
- [ ] Set version on about dialog
- [ ] Catched a rare exception when got a corrupted db from chrome (sqlite with OperationalError)
- [ ] Catched exception when open 2 instances (PermissionError (reading already open socket))
- [X] Catched exception when stop_wrapper deletes an wrapper_process
- [ ] Rewrite statusbar message core

FUTURE
- Fully remove browser login and cookie functionality
- Fully remove steamcompanion module
- Add support for new giveaway services
- Use Steam Guard and webapi for authentication
- Add api test scripts
